env:
    node: true
    es6: true
    mocha: true

extends:
    - airbnb-base
    - prettier

plugins:
    - prettier

globals:
    Atomic: readonly
    SharedArrayBuffer: readonly

parserOptions:
    ecmaVersion: 12
    sourceType: module

rules:
    prettier/prettier: error
    class-method-use-this: off
    no-param-reassign: off
    camelcase: off
    no-unused-vars:
        - error
        - argsIgnorePattern: next
    no-plusplus: off
